server:
  port: 8081

spring:
  application:
    name: restaurant-management-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/table_and_stock?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: your-very-long-and-secure-random-secret-key-for-jwt-signing-2026
